config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about",to: "homes#about"
  
  # 検索機能の実装 
  get "/search" => "searches#search"
  #ここまで
  
  devise_for :users

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]do
  
    resource :favorite, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
    
  end
  
  # フォロー/フォロワー機能の実装 %>
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  	get "followings" => "relationships#followings", as: "followings"
  	get "followers" => "relationships#followers", as: "followers"
    
    #投稿数の差
    get "search" => "users#search"
    #end
    
  end
  #ここまで
  
  
  #chat
  resources :chats, only: [:show, :create, :destroy]
  #end
  
  
  #group
  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    #上のdo＋下のendまで
    resource :group_users, only: [:create, :destroy]
    #追加・メール機能  
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
      
    end
  #end
  
  #タグ機能
  get "search_tag" => "bos#search_tag" 
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  

  
  belongs_to :user
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  
  has_many :post_comments, dependent: :destroy
  
  has_many :favorites, dependent: :destroy

  # 検索方法分岐
  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      Book.where('name LIKE ?', '%' + content)
    else
      Book.where('name LIKE ?', '%' + content + '%')
    end
  end
  
  #投稿数の前日比・前週比
  #scope :created_today, -> { where(created_at: Time.zone.now.all_day) } 
    #scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) } 
    #scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) } 
    #scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) } 
  #END
  
  #7日分の投稿数
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_2day_ago, -> { where(created_at: 2.day.ago.all_day) }
  scope :created_3day_ago, -> { where(created_at: 3.day.ago.all_day) }
  scope :created_4day_ago, -> { where(created_at: 4.day.ago.all_day) }
  scope :created_5day_ago, -> { where(created_at: 5.day.ago.all_day) }
  scope :created_6day_ago, -> { where(created_at: 6.day.ago.all_day) }
  #END
  
  #ソート機能
  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :star_count, -> {order(star: :desc)}
  #end
  
  #タグ機能(親子関係)
  has_many :booktags, dependent: :destroy
  has_many :tags, through: :booktags
  
  def save_booktags(tags)
    current_tags = self.booktags.pluck(:name) unless self.booktags.nil?
    
    old_tags = current_tags - tags
    
    new_tags = tags - current_tags
    
    old_tags.each do |old_name|
      self.booktags.delete Booktag.find_by(name:old_name)
    end
    
    new_tags.each do |new_name|
      booktag = Booktag.find_or_create_by(name:new_name)
      self.booktags << booktag
    end
  end
  #end
  
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :is_matching_login_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @new = Book.new
    @user = @book.user
    @post_comment = PostComment.new
    #タグ機能
    #@tag_list = @book.tags.pluck(:name).join(',')
    #@booktags = @book.tags
  end

  def index
    @book = Book.new
    #@books = Book.all
    @post_comment = PostComment.new
    #@books = Book.all.order(created_at: :desc)
    
    #タグ機能
    #@tag_list = Tag.all
    #リストの切り替え
    if params[:latest]
      @books = Book.latest
    elsif params[:old]
      @books = Book.old
    elsif params[:star_count]
      @books = Book.star_count
    else
      @books = Book.all
      
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    #タグ機能
    #tag_list = params[:book][:name].split(',')
    
    if @book.save
      #タグ機能
      #@book.save_tags(tag_list)
      
      redirect_to book_path(@book), notice: "本の投稿ができました"
    else
      @books = Book.all
      #render :index
    end
  end
  
  def search_tag
    @tag_list = Tag.all
    #@tag = Tag.find(params[:tag_id])
    @Book = @tag.books
  end
  

  def edit
    @book = Book.find(params[:id])
    @tag_list = @book.tags.pluck(:name).join(',')
  end

  def update
    @book = Book.find(params[:id])
    #タグ機能
    #tag_list=params[:book][:name].split(',')
    
    if @book.update(book_params)
      #タグ機能
      #@book.save_tags(tag_list)
      
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :image, :star)
  end
  
  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
  end
  
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<h2 class="mt-3">New book</h2>

<%= form_with model: book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  
  <%# star #%>
    <% if book.id.nil? %>
    <div class="form-group" id="star">
      <%= f.label :star %>
      <%= f.hidden_field :star, id: :review_star, class: 'form-control' %>
      <div id="post_raty"></div>
    </div>
    <script>
      $(document).on('turbolinks:load', function() {
        let elem = document.querySelector('#post_raty');
        if (elem == null) return;
  
        elem.innerHTML = ""
        let opt = {  
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          scoreName: 'book[star]',
        };
        raty(elem, opt);
      });
    </script>
  <% else %>
    <div class="form-group">
      <%= render "books/static.rate", book: book %>
    </div>
  <% end %>
  
  <label>タグ(,で区切ると複数タグ登録できます)</label>
  <%= f.text_field :name,value: @tag_list, class: 'form-control' %>
  

  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <%= link_to '新しい順', books_path(latest: "true") %>
  |<%= link_to '古い順', books_path(old: "true") %>
  |<%= link_to '評価の高い順', books_path(star_count: "true") %>
  
  
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>

      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
    
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>

        <td class=<%= "favorite_btn_" + book.id.to_s %> >
          <%= render "favorites/btn", book: book %>
        </td>
        
        <td><%= render "books/static.rate", book: book %></td>
        
        <td>
          <!--タグリスト-->
          <%#tag_list.each do |list|%>
            <i class="fa-sharp fa-solid fa-tag"></i>
            <%#=link_to list.name,search_tag_path(tag_id: list.id) %>
            <%#="(#{list.books.count})" %>
          <%# end %>
        </td>
        
        
        <td class="comments-count">
          コメント数：<%= book.post_comments.count %>
        </td>
        

        

      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_static.rate.html.erb
<div id="star_<%= book.id %>"></div>
<script>
$(document).on('turbolinks:load', function() {
  let elem = document.querySelector('#star_<%= book.id %>');
  if (elem == null) return;
  
  elem.innerHTML = "";
  let opt = {  
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: "<%= book.star %>",
    readOnly: true,
  };
  raty(elem, opt);
});
</script>

app/views/books/edit.html.erb
<%= render 'layouts/errors', obj: @book %>
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  		
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  
  <%= render 'layouts/errors', obj: @book  %>
  <div class='row'>
    <div class='col-md-3'>
      
      <%= render 'users/info', user: current_user %>
      
      <%= render 'form', book: @book %>
    </div>
    
    
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books, tag_list: @tag_list%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'users/info' , user: @user %>

      <%= render 'form', book: @new %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <table class='table'>
        <tr id="book_<%= @book.id %>">
          
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"75x75" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>

          <td class=<%= "favorite_btn_" + @book.id.to_s %>>
            <%= render "favorites/btn", book: @book %>
          </td>
          
          <td><%= render "static.rate", book: @book %></td>
          
          <td>
            <!-- タグリスト -->
            <%# @booktags.each do |tag| %>
            <i class="fa-sharp fa-solid fa-tag"></i>
              <%#= link_to tag.name,search_tag_path(tag_id: tag.id) %>
            <%# end %>
          </td>
          
          
          
          <% if @user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>
        </tr>
      </table>

      <div>
        <table class='table'>
        <% @book.post_comments.each do |post_comment| %>
        <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"75x75" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>

          <td>
            <%= post_comment.comment %>
          </td>

          <td>
            <% if post_comment.user == current_user %>
              <%= link_to 'Destroy',book_post_comment_path(@book.id,post_comment.id), method: :delete, class: "btn btn-sm btn-danger"%>
            <% end %>
          </td>
        <% end %>
        </tr>
      </table>
      </div>


      <div>
        <%= form_with model: [@book, @post_comment], local: false do |f| %>
          <%= f.text_area :comment, class: 'form-control book_body'%>
          <%= f.submit "送信" %>
        <% end %>
      </div>

    </div>
  </div>
</div>